name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Publish report to gh-pages
      if: always()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git fetch origin gh-pages

        git checkout gh-pages

        # Remove previous report
        rm -rf *

        # Copy the newly generated report
        cp -r ../playwright-report/* .

        # Add and commit the new report
        git add .

        git commit -m "Update test report" || echo "No changes to commit"

        # Push updated report
        git push origin gh-pages
